spring:
  profiles:
    active: Development,H2

server:
  port: 9000

---

spring:
  profiles: Development

  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: true

    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy

    properties:
      hibernate:
        show_sql: true
        format_sql: true

  jackson:
    serialization:
      INDENT_OUTPUT: true

---

spring:
  profiles: Production

  datasource:
    initialize: false

  jpa:
    hibernate:
      ddl-auto: update
